groups:
  - name: x-tok-alerts
    rules:
      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High request latency
          description: "95th percentile of request latency is above 1s for 5m"

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate
          description: "Error rate is above 5% for 5m"

      - alert: HighConcurrentRequests
        expr: http_requests_in_progress > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High number of concurrent requests
          description: "Number of concurrent requests is above 100 for 5m" 