global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "alert_rules.yml"
  - "first_rules.yml"
  - "second_rules.yml"

scrape_configs:
  - job_name: 'x-tok-backend'
    static_configs:
      - targets: ['localhost:22001']
    metrics_path: '/metrics' 